contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #slamseq channel"
    url: https://nfcore.slack.com/channels/slamseq
    about: Discussion about the nf-core/slamseq pipeline
